# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_help_list/app_help_list.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_help_index.app_help_index_test import (
    TestCaseAppHelpIndex as AppHelpIndex,
)


class TestCaseAppHelpList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("帮助详情——方案")
        .base_url("${ENV(static_url)}")
        .export(*["detail_id", "pid", "token", "id", "de_id"])
    )

    teststeps = [
        Step(
            RunTestCase("帮助中心首页")
            .call(AppHelpIndex)
            .export(*["id", "token", "detail_id", "pid"])
        ),
        Step(
            RunRequest("帮助中心——添加设备")
            .post("app/help/list")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "pid": "$pid",
                    "token": "$token",
                    "pkgname": "$pkgname",
                    "version": "$version",
                    "platform": "$platform",
                    "language": "$language",
                    "user_id": "$id",
                }
            )
            .extract()
            .with_jmespath("body.data[0].id", "de_id")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppHelpList().test_start()
