# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_service_service_data_list/app_service_service_data_list.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppServiceServiceDataList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-device_id-effecting-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "service_type": "${parameterize(test_data/service_type_data.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("服务页查询接口")
        .base_url("${ENV(api_url)}")
        .export(*["token", "id", "service_id"])
    )

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("服务页查询接口")
            .post("http://static-cn01.tange365.com/app/service/service_data/list")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "device_id": "$device_id",
                    "effecting": "$effecting",
                    "service_type": "$service_type",
                    "token": "$token",
                    "pkgname": "$pkgname",
                    "version": "$version",
                    "platform": "$platform",
                    "language": "$language",
                    "user_id": "$id",
                }
            )
            .extract()
            .with_jmespath("body.data.service[0].id", "service_id")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppServiceServiceDataList().test_start()
