# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/device/app_device_bind_user/app_device_bind_user.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppDeviceBindUser(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-uuid-bind_token": "${parameterize(test_data/normal_device_data.csv)}",
                "pkgname-push_id-push_channel-version-language": "${parameterize(test_data/common_app_param.csv)}",
                "status_code-ok-status-code-ids-ai_uuid": [
                    [200, 1, "ok", 200, 0, "AI"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备发起绑定").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("设备发起绑定")
            .post("http://device-cn01.tange365.com/app/device/bind/user")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid", "user_id": "$id", "bind_token": "$bind_token"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_startswith("body.data.ai_uuid", "$ai_uuid")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppDeviceBindUser().test_start()
