# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_device_list/app_device_list.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppDeviceList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "pkgname-push_id-push_channel-version-language": "${parameterize(test_data/common_app_param.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备列表").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("设备列表")
            .post("/api/device/list")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "limit": 200,
                    "language": "$language",
                    "version": "$version",
                    "token": "$token",
                    "page": 1,
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_greater_than("body.data.items[0].id", "$ids")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppDeviceList().test_start()
