# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_bell_alarm_audio_list/app_bell_alarm_audio_list.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppBellAlarmAudioList(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-ido": [[200, 1, "ok", 200, 0, "0"]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备警铃列表").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("设备警铃列表")
            .post("app/bell/alarm/audio/list")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "pkgname": "$pkgname",
                    "audio_format": "g711",
                    "platform": "$platform",
                    "file_format": "wav",
                    "language": "$language",
                    "version": "$version",
                    "token": "$token",
                    "volume_level": 1,
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_greater_than("body.data[0].id", "$ido")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppBellAlarmAudioList().test_start()
