# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/personal_new_edit/personal_new_edit.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.personal_index.personal_index_test import (
    TestCasePersonalIndex as PersonalIndex,
)


class TestCasePersonalNewEdit(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "push_params": "${parameterize(test_data/push_params.csv)}",
                "username-pwd-platform-device_id-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-idss": [[200, 1, "ok", 200, 0, "0"]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("personal/index").base_url("${ENV(api_url)}")

    teststeps = [
        Step(
            RunTestCase("获取登录token")
            .call(PersonalIndex)
            .export(*["id", "token", "push_interval", "is_push"])
        ),
        Step(
            RunRequest("personal/new_edit")
            .post("personal/new_edit")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "device_id": "$device_id",
                    "is_push": "$is_push",
                    "language": "$language",
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "push_interval": "$push_interval",
                    "push_params": ["$push_params"],
                    "token": "$token",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_greater_than("body.data.id", "$idss")
        ),
    ]


if __name__ == "__main__":
    TestCasePersonalNewEdit().test_start()
