# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_user_delete_alarm_msg/app_user_delete_alarm_msg.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_query_alarm_msg.app_user_query_alarm_msg_test import (
    TestCaseAppUserQueryAlarmMsg as AppUserQueryAlarmMsg,
)


class TestCaseAppUserDeleteAlarmMsg(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "message_type": "${parameterize(test_data/message_type_data.csv)}",
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-token": [
                    [200, 1, "ok", 200, 0, "_app"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("删除告警消息").base_url("${ENV(api_url)}")

    teststeps = [
        Step(
            RunTestCase("告警消息页").call(AppUserQueryAlarmMsg).export(*["token", "msg_id"])
        ),
        Step(
            RunRequest("删除告警消息")
            .post("app/user/delete/alarm_msg")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "del_type": 1,
                    "language": "$language",
                    "msg_id": "$msg_id",
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "token": "$token",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppUserDeleteAlarmMsg().test_start()
