# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_geofence_create/app_geofence_create.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppGeofenceCreate(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-uuid-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("创建电子围栏").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("创建电子围栏")
            .post("app/geofence/create")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "center": "114.06338638913459,22.66348470750846",
                    "id": 4661,
                    "language": "$language",
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "radius": 5000,
                    "switch": 1,
                    "token": "$token",
                    "uuid": "$uuid",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppGeofenceCreate().test_start()
