# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/device/device_auth_get_bind_status/device_auth_get_bind_status.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDeviceAuthGetBindStatus(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "uuid": "${parameterize(test_data/normal_device_data.csv)}",
                "status_code-ok-status-code-is_bind": [[200, 1, "ok", 200, 1]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iiCam365 设备获取绑定状态").base_url("${ENV(DV_test_url)}")

    teststeps = [
        Step(
            RunRequest("设备获取绑定状态")
            .post("device/auth/get_bind_status")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_equal("body.data.is_bind", "$is_bind")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeviceAuthGetBindStatus().test_start()
