# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_user_query_alarm_msg/app_user_query_alarm_msg.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppUserQueryAlarmMsg(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "message_type": "${parameterize(test_data/message_type_data.csv)}",
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-token": [
                    [200, 1, "ok", 200, 0, "_app"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("告警消息页").base_url("${ENV(api_url)}").export(*["token", "msg_id"])

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("告警消息页")
            .post("app/user/query/alarm_msg")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "end_timestamp": 1616465128,
                    "language": "$language",
                    "limit": 30,
                    "message_type": ["$message_type"],
                    "page": 1,
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "start_timestamp": 1616428800,
                    "token": "$token",
                    "version": "$version",
                }
            )
            .extract()
            .with_jmespath("body.data.items[0].msg_id", "msg_id")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppUserQueryAlarmMsg().test_start()
