# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/device_unshare/device_unshare.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseDeviceUnshare(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-device_id-account-pkgname-push_id-push_channel-version": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "language-status_code-ok-status-code-ids": [
                    ["zh-cn", 200, 1, "ok", 200, 0, "0"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备分享列表").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("取消分享")
            .post("device/unshare")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "account": "$account",
                    "device_id": "$device_id",
                    "language": "$language",
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "token": "$token",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeviceUnshare().test_start()
