# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/api_device_unbind/api_device_unbind.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.api_device_bind.api_device_bind_test import (
    TestCaseApiDeviceBind as ApiDeviceBind,
)


class TestCaseApiDeviceUnbind(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-uuid-add_type-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_unbind_data.csv)}",
                "status_code-ok-status-code-ids-device_id": [[200, 1, "ok", 200, 0, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备解绑").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("App发起绑定").call(ApiDeviceBind).export(*["id", "token"])),
        Step(
            RunRequest("设备解绑")
            .post("/device/unbind")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "version": "$version",
                    "language": "$language",
                    "platform": "$platform",
                    "device_id": "$id",
                    "token": "$token",
                    "pkgname": "$pkgname",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseApiDeviceUnbind().test_start()
