# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/device_record_info/device_record_info.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_device_list_least.app_device_list_least_test import (
    TestCaseAppDeviceListLeast as AppDeviceListLeast,
)


class TestCaseDeviceRecordInfo(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-device_ids": [
                    [200, 1, "ok", 200, 0, "0"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iCam365-设备警铃列表").base_url("${ENV(api_url)}")

    teststeps = [
        Step(
            RunTestCase("获取登录token")
            .call(AppDeviceListLeast)
            .export(*["device_id", "id", "token", "uuid"])
        ),
        Step(
            RunRequest("设备警铃列表")
            .post("device/record_info")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "device_id": "$device_id",
                    "end_time": "${get_last_today()}",
                    "language": "$language",
                    "limit": 50,
                    "page": 1,
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "start_time": "${get_zero_today()}",
                    "token": "$token",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeviceRecordInfo().test_start()
