# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/static_img_customer/static_img_customer.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseStaticImgCustomer(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"status_code": [200]}))
    def test_start(self, param):
        super().test_start(param)

    config = Config("static/img/customer@2x.cbed55d1.png").base_url(
        "${ENV(static_url)}"
    )

    teststeps = [
        Step(
            RunRequest("static/img/customer@2x.cbed55d1.png")
            .get("static/img/customer@2x.cbed55d1.png")
            .with_headers(**{"Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", "$status_code")
        ),
    ]


if __name__ == "__main__":
    TestCaseStaticImgCustomer().test_start()
