# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/shop_ai/shop_ai.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseShopAi(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-device_id-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iCam365-我的智能识别服务").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("我的智能识别服务")
            .get(
                "/shop/ai?user_id=$id&device_id=$device_id&language=$language&pkgname=$pkgname&token=$token&version=$version&platform=$platform"
            )
            .with_headers(**{"Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", "$status_code")
        ),
    ]


if __name__ == "__main__":
    TestCaseShopAi().test_start()
