# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_device_get_bind_history/app_device_get_bind_history.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppDeviceGetBindHistory(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-token": [
                    [200, 1, "ok", 200, 0, "_app"]
                ],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iCam365-查询历史绑定记录接口").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("查询历史绑定记录接口")
            .post("app/device/get_bind_history")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"token": "$token"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppDeviceGetBindHistory().test_start()
