# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/api_auth_get_privacy/api_auth_get_privacy.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseApiAuthGetPrivacy(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "platform-language": "${parameterize(test_data/normal_forget_data.csv)}",
                "status_code-ok-status-code-data": [[200, 1, "ok", 200, "https://"]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iCam365-隐私策略").base_url("${ENV(api_url)}")

    teststeps = [
        Step(
            RunRequest("隐私策略")
            .post("api/auth/get_privacy")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"language": "$language", "platform": "$platform"})
            .extract()
            .with_jmespath("body.data", "link")
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_startswith("body.data", "$data")
        ),
        Step(
            RunRequest("请求data返回的链接")
            .get("$link")
            .with_headers(**{"Content-Type": "application/json"})
            .validate()
            .assert_equal("status_code", "$status_code")
        ),
    ]


if __name__ == "__main__":
    TestCaseApiAuthGetPrivacy().test_start()
