# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_device_report/app_device_report.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseAppDeviceReport(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "uuid": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids": [[200, 1, "ok", 200, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("设备上报日志").base_url("${ENV(api_url)}")

    teststeps = [
        Step(
            RunRequest("设备上报日志")
            .post("app/device/report")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppDeviceReport().test_start()
