# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/service/app_car_route_current_position/app_car_route_current_position.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcases.service.app_user_login.app_user_login_test import (
    TestCaseAppUserLogin as AppUserLogin,
)


class TestCaseAppCarRouteCurrentPosition(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-pwd-platform-uuid-pkgname-push_id-push_channel-version-language": "${parameterize(test_data/normal_device_bind_data.csv)}",
                "status_code-ok-status-code-ids-latitude": [[200, 1, "ok", 200, 0, 0]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("行车轨迹").base_url("${ENV(api_url)}")

    teststeps = [
        Step(RunTestCase("获取登录token").call(AppUserLogin).export(*["id", "token"])),
        Step(
            RunRequest("行车轨迹")
            .post("app/car_route/current_position")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "language": "$language",
                    "pkgname": "$pkgname",
                    "platform": "$platform",
                    "token": "$token",
                    "uuid": "$uuid",
                    "version": "$version",
                }
            )
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
            .assert_greater_than("body.data.latitude", "$latitude")
        ),
    ]


if __name__ == "__main__":
    TestCaseAppCarRouteCurrentPosition().test_start()
