# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/device/device_start_interaction/device_start_interaction.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDeviceStartInteraction(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "source-version-iccid-uuid-actived-password": "${parameterize(test_data/normal_device_data.csv)}",
                "status_code-ok-status-code": [[200, 1, "ok", 200]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iiCam365 设备启动交互流程")

    teststeps = [
        Step(
            RunRequest("调度服务")
            .post("http://ep.test.tange365.com/service")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "source": "$source",
                    "deviceid": "$uuid",
                    "version": "$version",
                    "iccid": "$iccid",
                }
            )
        ),
        Step(
            RunRequest("获取当前服务器时间")
            .post("http://device-test.tange365.com/device/record/time")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(None)
        ),
        Step(
            RunRequest("激活设备")
            .post("http://device-test.tange365.com/device/auth/active")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid", "actived": "$actived"})
        ),
        Step(
            RunRequest("设备获取绑定状态")
            .post("http://device-test.tange365.com/device/auth/get_bind_status")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid"})
        ),
        Step(
            RunRequest("设备获取绑定参数")
            .post("http://device-test.tange365.com/device/auth/get_bind_params")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid"})
        ),
        Step(
            RunRequest("设置设备P2P连接密码")
            .post("http://device-test.tange365.com/device/auth/password")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid", "password": "$password"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeviceStartInteraction().test_start()
