# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/device/device_auth_password/device_auth_password.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDeviceAuthPassword(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "uuid-password": "${parameterize(test_data/normal_device_data.csv)}",
                "status_code-ok-status-code": [[200, 1, "ok", 200]],
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("tange-iiCam365 设置设备P2P连接密码").base_url("${ENV(DV_test_url)}")

    teststeps = [
        Step(
            RunRequest("设置设备P2P连接密码")
            .post("device/auth/password")
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({"uuid": "$uuid", "password": "$password"})
            .validate()
            .assert_equal("status_code", "$status_code")
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.ok", "$ok")
            .assert_equal("body.status", "$status")
            .assert_equal("body.code", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeviceAuthPassword().test_start()
